In [1]:
#decision tree
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.model_selection import cross_val_score

In [2]:
# model
clf_gini = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=3, min_samples_leaf=5) 


In [3]:
import pandas as pd
ff = pd.read_csv('FOREST_FIRE.csv')
ff.head()

Unnamed: 0  X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  \
0           0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   
1           1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   
2           2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   
3           3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   
4           4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   

   area  category  FF     BUI      FWI  
0   0.0  Low_risk   0   60.25   32.675  
1   0.0  Low_risk   0  352.25  179.475  
2   0.0  Low_risk   0  365.30  186.000  
3   0.0  Low_risk   0   55.40   32.200  
4   0.0  Low_risk   0   76.75   43.175

In [4]:
pred1 = pd.DataFrame(ff[['FFMC','DMC','DC','ISI','wind','RH','temp','area']],columns=['FFMC','DMC','DC','ISI','wind','RH','temp','area'])
target = pd.DataFrame(ff.FF,columns = ['FF'])


In [5]:
X_train, X_test, y_train, y_test = train_test_split(pred1, target, test_size=0.33, random_state=42)

In [6]:
# Training the mode
clf_gini.fit(X_train,y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [7]:
# predicting through the model
y_pred = clf_gini.predict(X_train)
y_pred = pd.DataFrame(y_pred, columns = ["predictedvalue"])
y_pred.count()


predictedvalue    346
dtype: int64

In [8]:
# calculataing training error
confusion_matrix(y_train, y_pred) 

array([[161,   0],
       [  0, 185]], dtype=int64)

In [9]:
accuracy_score(y_train,y_pred)

1.0

In [10]:
# Test data prediction
y_pret = clf_gini.predict(X_test)
y_pret = pd.DataFrame(y_pret, columns = ["predictedvalue"])
y_pret.head()

predictedvalue
0               0
1               0
2               1
3               1
4               1

In [11]:
# Test error
confusion_matrix(y_pret,y_test)

array([[86,  0],
       [ 0, 85]], dtype=int64)

In [12]:
accuracy_score(y_pret,y_test)

1.0

In [13]:
pred2 = pd.DataFrame(ff[['FFMC','DMC','DC','ISI','wind','RH','temp']],columns=['FFMC','DMC','DC','ISI','wind','RH','temp'])
target2 = pd.DataFrame(ff.FF,columns = ['FF'])
pred2.head()

FFMC   DMC     DC  ISI  wind  RH  temp
0  86.2  26.2   94.3  5.1   6.7  51   8.2
1  90.6  35.4  669.1  6.7   0.9  33  18.0
2  90.6  43.7  686.9  6.7   1.3  33  14.6
3  91.7  33.3   77.5  9.0   4.0  97   8.3
4  89.3  51.3  102.2  9.6   1.8  99  11.4

In [14]:
X_train, X_test, y_train, y_test = train_test_split(pred2, target2, test_size=0.33, random_state=42)

In [15]:
# model
clf_gini1 = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=3, min_samples_leaf=5) 
clf_gini1.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [16]:
y_pred = pd.DataFrame(clf_gini1.predict(X_train), columns = ["predictedvalue"])

In [17]:
confusion_matrix(y_train,y_pred)

array([[ 49, 112],
       [ 21, 164]], dtype=int64)

In [18]:
clf_gini1.predict(X_test)
y_pred1 = pd.DataFrame(clf_gini1.predict(X_test), columns = ["predictedvalue"])
y_pred1.count()

predictedvalue    171
dtype: int64

In [19]:
confusion_matrix(y_test,y_pred1)

array([[17, 69],
       [16, 69]], dtype=int64)

In [20]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.52      0.20      0.29        86
           1       0.50      0.81      0.62        85

   micro avg       0.50      0.50      0.50       171
   macro avg       0.51      0.50      0.45       171
weighted avg       0.51      0.50      0.45       171



In [21]:
# BAGGING MODELTO IMPROVE CLASSIFIER
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

X = pred2
Y = target2
seed = 7
kfold = model_selection.KFold(n_splits=25, random_state=seed)
cart = DecisionTreeClassifier()
num_trees = 200
clf_gini2 = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=3, min_samples_leaf=5) 
model = BaggingClassifier(base_estimator=clf_gini2, n_estimators=num_trees, random_state=seed)
model2 = BaggingClassifier(base_estimator=cart, n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results)


C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:621: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:621: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:621: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:621: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

[0.52380952 0.14285714 0.19047619 0.28571429 0.28571429 0.61904762
 0.61904762 0.42857143 0.28571429 0.33333333 0.14285714 0.61904762
 0.57142857 0.42857143 0.47619048 0.47619048 0.66666667 0.45
 0.6        0.6        0.6        0.3        0.45       0.55
 0.6       ]


In [22]:
model.fit(X,Y)

C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:621: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=200, n_jobs=None, oob_score=False,
         random_state=7, verbose=0, warm_start=False)

In [23]:
model2.fit(X_train,y_train)

C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:621: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=200, n_jobs=None, oob_score=False,
         random_state=7, verbose=0, warm_start=False)

In [24]:
y_pr1 = model2.predict(X_test)


In [25]:
y_pr = model.predict(X_test)

In [26]:
confusion_matrix(y_test,y_pr)
confusion_matrix(y_test,y_pr1)

array([[42, 44],
       [36, 49]], dtype=int64)

In [27]:
m1 =BaggingClassifier.score(model2,X_test,y_test)
m2 = BaggingClassifier.score(model,X_test,y_test)
print(m1,m2)                        

0.5321637426900585 0.7192982456140351


   ## Boosting
    

In [28]:
from sklearn.ensemble import AdaBoostClassifier
AdaBoost = AdaBoostClassifier(base_estimator= clf_gini2,n_estimators=400,learning_rate=1)
AdaBoost = AdaBoostClassifier(n_estimators=400,learning_rate=1,algorithm='SAMME')
AdaBoost.fit(X,Y)
prediction = AdaBoost.score(X,Y)
print('The accuracy is: ',prediction*100,'%')

C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


The accuracy is:  67.50483558994198 %


In [29]:
from sklearn.ensemble import AdaBoostClassifier
AdaBoost1 = AdaBoostClassifier(base_estimator= cart,n_estimators=400,learning_rate=1)
AdaBoost1 = AdaBoostClassifier(n_estimators=400,learning_rate=1,algorithm='SAMME')
AdaBoost1.fit(X,Y)
prediction = AdaBoost.score(X,Y)
print('The accuracy is: ',prediction*100,'%')

C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


The accuracy is:  67.50483558994198 %


## Random forest 

In [30]:
#let  us use Random forest algorithm and check the model
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)


C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\SKR\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  import sys


In [31]:
from sklearn.ensemble import RandomForestClassifier

Classifier = RandomForestClassifier(n_estimators=60, random_state=0,)  
Classifier.fit(X_train, y_train)  
y_pred = Classifier.predict(X_test)

C:\Users\SKR\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [32]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[43 43]
 [30 55]]
              precision    recall  f1-score   support

           0       0.59      0.50      0.54        86
           1       0.56      0.65      0.60        85

   micro avg       0.57      0.57      0.57       171
   macro avg       0.58      0.57      0.57       171
weighted avg       0.58      0.57      0.57       171

0.5730994152046783


## f1-0.59 

   ### Let us try increasing the accuray by adding one variable

In [33]:
#one_hot_encoding
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [34]:
data = (ff.month)
print(data)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(data)
print(integer_encoded)

0      mar
1      oct
2      oct
3      mar
4      mar
5      aug
6      aug
7      aug
8      sep
9      sep
10     sep
11     sep
12     aug
13     sep
14     sep
15     sep
16     mar
17     oct
18     mar
19     apr
20     sep
21     sep
22     jun
23     aug
24     aug
25     aug
26     sep
27     sep
28     sep
29     sep
      ... 
487    aug
488    aug
489    aug
490    aug
491    aug
492    aug
493    aug
494    aug
495    aug
496    aug
497    aug
498    aug
499    aug
500    aug
501    aug
502    aug
503    aug
504    aug
505    aug
506    aug
507    aug
508    aug
509    aug
510    aug
511    aug
512    aug
513    aug
514    aug
515    aug
516    nov
Name: month, Length: 517, dtype: object
[ 7 10 10  7  7  1  1  1 11 11 11 11  1 11 11 11  7 10  7  0 11 11  6  1
  1  1 11 11 11 11 11 11 11 11 11 11 10 10 10  7  5  1  1 11 11 11 11  5
  7  7 11  1  1  1  1 11 11 10  3  3  7  7  1  1  1  1 11 11 11  7  7 11
  7  1 11  3  3  7  1  1  1  1  1  1  1 11 11 11 11  7  1  7  1  1  1 

In [35]:
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [36]:
# invert encoding
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['mar']


In [37]:
fire = ff
fire['month'] = onehot_encoded
fire.head()

Unnamed: 0  X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  \
0           0  7  5    0.0  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   
1           1  7  4    0.0  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   
2           2  7  4    0.0  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   
3           3  8  6    0.0  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   
4           4  8  6    0.0  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   

   area  category  FF     BUI      FWI  
0   0.0  Low_risk   0   60.25   32.675  
1   0.0  Low_risk   0  352.25  179.475  
2   0.0  Low_risk   0  365.30  186.000  
3   0.0  Low_risk   0   55.40   32.200  
4   0.0  Low_risk   0   76.75   43.175

In [38]:
resp = pd.DataFrame(ff[['month','FFMC','DMC','DC','ISI','wind','RH','temp']],columns=['month','FFMC','DMC','DC','ISI','wind','RH','temp'])
tar = pd.DataFrame(ff.FF,columns = ['FF'])

In [39]:
X_train, X_test, y_train, y_test = train_test_split(resp, tar, test_size=0.33, random_state=42)

In [40]:
# model
gini1 = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=3, min_samples_leaf=5) 
gini1.fit(X_train,y_train)
model2 = DecisionTreeClassifier()
model2.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [41]:
ypgini = gini1.predict(X_test)
ypm2 = model2.predict(X_test)

In [42]:
confusion_matrix(y_test,ypgini)
confusion_matrix(y_test,ypm2)

array([[39, 47],
       [41, 44]], dtype=int64)

In [43]:
print(classification_report(y_test,ypgini))
print(classification_report(y_test,ypm2))

              precision    recall  f1-score   support

           0       0.52      0.20      0.29        86
           1       0.50      0.81      0.62        85

   micro avg       0.50      0.50      0.50       171
   macro avg       0.51      0.50      0.45       171
weighted avg       0.51      0.50      0.45       171

              precision    recall  f1-score   support

           0       0.49      0.45      0.47        86
           1       0.48      0.52      0.50        85

   micro avg       0.49      0.49      0.49       171
   macro avg       0.49      0.49      0.48       171
weighted avg       0.49      0.49      0.48       171



In [44]:
model_gini = BaggingClassifier(base_estimator=gini1, n_estimators=num_trees, random_state=seed)
model_m2 = BaggingClassifier(base_estimator=model2, n_estimators=num_trees, random_state=seed)

In [45]:
model_gini.fit(X_train,y_train)
model_m2.fit(X_train,y_train)

C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:621: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\SKR\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:621: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=200, n_jobs=None, oob_score=False,
         random_state=7, verbose=0, warm_start=False)

In [46]:
s1 =BaggingClassifier.score(model_gini,X_test,y_test)
s2 = BaggingClassifier.score(model_m2,X_test,y_test)
print(s1,s2)

0.5672514619883041 0.5321637426900585
